apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-cadvisor
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-cadvisor
  template:
    metadata:
      labels:
        app: kubernetes-cadvisor
    spec:
      containers:
      - name: kubernetes-cadvisor
        image: gcr.io/google-containers/cadvisor:latest
        ports:
        - containerPort: 8443
