apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service-endpoints
  namespace: monitoring
spec:
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app: kubernetes-service-endpoints  # Asegúrate de que la etiqueta 'app' coincida con las etiquetas de los pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-service-endpoints
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-service-endpoints
  template:
    metadata:
      labels:
        app: kubernetes-service-endpoints
    spec:
      containers:
        - name: kubernetes-service-endpoints
          image: gcr.io/google-containers/cadvisor:latest  # Usa la imagen correcta aquí
          ports:
            - containerPort: 443  # El puerto en el que el contenedor estará escuchando

