apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: node-exporter  # Asegúrate de que la etiqueta 'app: node-exporter' coincida con las etiquetas de los pods

