apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-nodes'
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']

      - job_name: 'kubernetes-pods'
        static_configs:
          - targets: ['pod1.monitoring.svc.cluster.local:8081', 'pod2.monitoring.svc.cluster.local:8082']

      - job_name: 'kubernetes-apiservers'
        static_configs:
          - targets: ['kubernetes.default.svc.cluster.local:444']

      - job_name: 'kubernetes-cadvisor'
        static_configs:
          - targets: ['kubernetes-cadvisor.monitoring.svc.cluster.local:8443']

      - job_name: 'kubernetes-service-endpoints'
        static_configs:
          - targets: ['kubernetes-service-endpoints.monitoring.svc.cluster.local:443']

      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.monitoring.svc.cluster.local:9100']





