apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce  # Permite que un solo pod tenga acceso a los datos
  resources:
    requests:
      storage: 5Gi  # Ajusta el tamaño según tus necesidades
  storageClassName: hostpath   # Usar la StorageClass disponible
