apiVersion: v1
kind: Service
metadata:
  name: flask-predictive-model-service
spec:
  selector:
    app: flask-predictive-model
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort

